Custom Guide Shape
mreram/ShowCaseView pull request #41
Opened 2020-09-29 02:31 UTC by NicholasMata

Extends existing functionality to allow for a custom guide shape. 

This is done through the use of a new interface called `Targetable`.

### How it works
If the target view given to the `GuideView` constructor implements `Targetable`. 
* `boundingRect` will be used to set `targetRect` property inside the `GuideView` class. 
* `guidePath` will be used when `onDraw` is called in `GuideView` instead of always using `drawRoundRect` the canvas will call `drawPath` and will draw the guide path.

**PS: I have added onto the sample application with a demonstration of how this works as well.**

2020-10-03 07:23 UTC, mreram commented
Thanks for your contribution, I will review this ASAP.

2020-10-03 17:31 UTC, mreram commented on app/src/main/java/ir/smartdevelop/eram/showcaseview/CircleView.java
> +    private static final int DEFAULT_CIRCLE_COLOR = Color.RED;
Add a space above this

2020-10-03 17:31 UTC, mreram commented on app/src/main/java/ir/smartdevelop/eram/showcaseview/CircleView.java
> +
Please remove this space

2020-10-03 17:35 UTC, mreram commented on app/src/main/java/ir/smartdevelop/eram/showcaseview/CircleView.java
> +    private int circleColor = DEFAULT_CIRCLE_COLOR;
Please add an underline before `circleColor` like other fields or remove other underlines.

2020-10-03 17:37 UTC, mreram requested changes
Please review my comments.

2020-10-06 16:25 UTC, NicholasMata commented on app/src/main/java/ir/smartdevelop/eram/showcaseview/CircleView.java
> +    private int circleColor = DEFAULT_CIRCLE_COLOR;
Nice catch

2020-10-06 16:26 UTC, NicholasMata commented
If you could review again I made the requested changes. Let me know if I need to do anything else.

2020-10-06 16:35 UTC, merged